# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da45a8a4661c8ebdb4c330a87b9fc51201a90c6d66c6979d4454b0e92a03cc765bd2cab146b9c77a33343d9e3e09b0a7ef03ed4f40639ecf1fc784bdfb821736

test:
  secret_key_base: c3b637c48c7ad9f85f9dcea6a725d20250309496e073b26885efd13432e65ebe21c036a41c0346d727337db339effd46ef11a4f032b08369960389ad68b3f3e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
